"""Unit tests for pit38.data_sources.csv_utils.

The open_csv_reader utility is the centerpiece of the fix for #33: it
tolerates UTF-8 BOM and normalizes headers so downstream code doesn't
need to worry about broker-specific quirks. These tests pin the
behaviour so future refactors don't regress it.
"""
import os
import tempfile
from unittest import TestCase

from pit38.data_sources.csv_utils import open_csv_reader


BOM = b"\xef\xbb\xbf"


class TestOpenCsvReader(TestCase):
    def setUp(self):
        self.tmp = tempfile.NamedTemporaryFile(
            mode="wb", suffix=".csv", delete=False
        )
        self.tmp.close()
        self.path = self.tmp.name

    def tearDown(self):
        os.unlink(self.path)

    def _write_bytes(self, content: bytes) -> None:
        with open(self.path, "wb") as f:
            f.write(content)

    # ─── BOM handling ───────────────────────────────────────

    def test_strips_utf8_bom_from_first_column(self):
        """File with UTF-8 BOM at the start: first column name should
        come out clean, no \\ufeff prefix."""
        self._write_bytes(BOM + b"date,ticker\n2024-01-01,AAPL\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker"])
            rows = list(reader)
            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0]["date"], "2024-01-01")
            self.assertEqual(rows[0]["ticker"], "AAPL")

    def test_no_bom_still_works(self):
        """Files without BOM (our own output, Linux-generated) read
        identically — utf-8-sig is a no-op in that case."""
        self._write_bytes(b"date,ticker\n2024-01-01,AAPL\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker"])

    def test_bom_in_middle_of_file_is_not_stripped(self):
        """Sanity: only leading BOM is handled. We don't aggressively
        strip BOMs anywhere in the file (that would be destructive)."""
        self._write_bytes(b"date,ticker\n2024-01-01," + BOM + b"AAPL\n")

        with open_csv_reader(self.path) as reader:
            rows = list(reader)
            # The BOM is preserved in the data (we only cared about the header)
            self.assertEqual(rows[0]["ticker"], "﻿AAPL")

    # ─── Header normalization ───────────────────────────────

    def test_headers_lowercased(self):
        """Mixed-case broker headers become stable lowercase form."""
        self._write_bytes(b"Date,Ticker,TYPE\n2024-01-01,AAPL,BUY\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker", "type"])

    def test_headers_stripped(self):
        """Leading/trailing whitespace in headers (common in exports
        generated by Excel) is stripped."""
        self._write_bytes(b" Date , Ticker\n2024-01-01,AAPL\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker"])

    def test_multi_word_headers_preserve_internal_spaces(self):
        """`Total Amount` becomes `total amount` — internal spaces
        preserved, only edges stripped."""
        self._write_bytes(b"Date,Total Amount\n2024-01-01,100.00\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "total amount"])

    def test_bom_and_case_together(self):
        """The combination that broke #33 — BOM plus capital D —
        should yield a clean lowercase 'date' header."""
        self._write_bytes(BOM + b"Date,Ticker\n2024-01-01,AAPL\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker"])

    # ─── Edge cases ─────────────────────────────────────────

    def test_empty_file_has_no_fieldnames(self):
        """Empty file: no crash, no fieldnames."""
        self._write_bytes(b"")

        with open_csv_reader(self.path) as reader:
            self.assertIsNone(reader.fieldnames)

    def test_header_only_yields_no_rows(self):
        """Header but no data rows: iteration yields nothing."""
        self._write_bytes(b"date,ticker\n")

        with open_csv_reader(self.path) as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker"])
            self.assertEqual(list(reader), [])

    def test_custom_delimiter(self):
        """Supports tab-separated files as a use case for future
        brokers (e.g. some older exports)."""
        self._write_bytes(b"date\tticker\n2024-01-01\tAAPL\n")

        with open_csv_reader(self.path, delimiter="\t") as reader:
            self.assertEqual(reader.fieldnames, ["date", "ticker"])
            rows = list(reader)
            self.assertEqual(rows[0]["ticker"], "AAPL")

    def test_context_manager_closes_file(self):
        """Verify file is closed when context exits. Regression guard
        against leaked file descriptors in long-running tools."""
        with open_csv_reader(self.path) as reader:
            handle = reader.reader  # underlying _csv.reader
            # We can't easily check the backing file is open, but we can
            # at least ensure no exception is raised on context exit.
            pass
        # After context exit, attempting to iterate the raw reader
        # should fail because the file is closed
        with self.assertRaises(ValueError):
            # ValueError: I/O operation on closed file
            next(iter(handle))
